config/routes.rb
ItalyabroadNew::Application.routes.draw do
  namespace :admin do
    resources :testimonials
    resources :faqs
    resources :shipping_agencies
    resources :occasions
    resources :about_us
    resources :contact_messages
    resources :regions do
      resources :images, :only => [:destroy]
    end
    resources :producers  do
      resources :images, :only => [:destroy]
    end
    resources :grapes do
      resources :images, :only => [:destroy]
    end
    resources :forums
    resources :categories
    resources :deliveries
    resources :cupons do
      match :product_list, :on => :collection
    end
    resources :forums
    resources :posts
    resources :comments
    resources :reviews do
      match :send_mails, :on => :collection
    end
    resources :orders, :only => [:index, :show, :destroy] do
      member do
        get :print_tasting
        get :print_invoice
        get :print_picking_list
        get :delivery_details
        get :cancel_delivery_charge
      end
    end
    resources :users
    resources :customers do
      collection do
        get :print_user_details
      end
    end
    resources :gift_options
    resources :subscriptions
    resources :news_letters do
      resources :images, :only => [:destroy]
    end
    resources :recipes do
      collection do 
        get 'xml'
      end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :resources, :only => [:destroy]
    resources :images, :only => [:destroy]
    resources :products do
       collection do 
          get 'xml'
        end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :settings, :only => [:index, :update] do
      
      collection do 
        get 'available_backups'
        get 'restore'
        get 'take_backup_now'
        get 'download'

      end

      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :small_box_settings 
    get "moods/index"

    get "moods/new"

    post "moods/create"

    get "moods/edit"

    put "moods/update"
    delete "moods/destroy"
  end

  get "moods/index"

  resources :chat_messages do
    collection do
      get "show_alert"
      get "take_username" => "chat_messages#take_username"
    end
  end

  namespace(:admin){
    resources :wine_sizes
    resources :sommeliers
    resources :food_or_drinks
    resources :desired_expenditures
    resources :food_options
    resources :manage_sommeliers, :only => [:index, :create]
  }

  match "/auth/:provider/callback" => "site/authentications#create"

  match 'suppliers' => 'site/base#supplier', :as => :meet_us
  match 'contact-us' => 'site/base#contact', :as => :contact_us
  match 'corporate-services' => 'site/base#corporate', :as => :corporate
  match 'wholesale-enquiry' => 'site/base#enquiries', :as => :wholesale_enquiry
  match 'olive-oil-guide' => 'site/base#olive_oil_guide', :as => :olive_oil_guide
  match 'about-us' => 'site/base#about_us', :as => :about_us
  match 'our-manifesto' => 'site/base#our_principles', :as => :our_principles
  match 'meet-us' => 'site/base#meet_us', :as => :meet_us
  match 'terms-and-conditions' => 'site/base#conditions', :as => :terms_and_conditions
  match 'privacy-policy' => 'site/base#privacy', :as => :privacy_policy
  match 'delivery-services' => 'site/base#delivery_services', :as => :delivery_services
  match 'managing-account' => 'site/base#managing_account', :as => :managing_account
  match 'contact-details' => 'site/base#contact_details', :as => :contact_details
  match 'sitemap' => 'site/base#sitemap', :as => :sitemap
  match 'google_sitemap.xml' => 'site/base#google_sitemap', :defaults => {:format => :xml}
  match 'guarantee_of_satisfaction' => 'site/base#guarantee_of_satisfaction', :as => :guarantee_of_satisfaction
  match 'enable_disable_chat' => 'admin/base#enable_disable_chat', :as => :enable_disable_chat
  match 'testimonial' => 'site/testimonials#index', :as => :testimonial
  match 'popular' => 'site/base#popular', :as => :popular
  match 'signup' => 'site/customers#new', :as => :signup
  match 'login' => 'site/base#login', :as => :login
  match 'guest_login' => 'site/base#guest_login', :as => :guest_login
  match 'logout' => 'site/base#logout', :as => :logout
  match 'subscribe-dali-news' => 'site/base#subscribe', :as => :subscribe_dali_news
  match 'subscriptions' => 'site/base#create_subscription', :as => :create_subscription, :method => :post
  match 'thank-you' => 'site/base#subscription_complete', :as => :subscription_complete
  match 'unsubscribe-dali-news' => 'site/base#unsubscribe', :as => :unsubscribe_dali_news
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  match 'siteadmin' => 'admin/base#index', :as => :siteadmin
  match 'admin/login' => 'admin/base#login', :as => :admin_login
  get '/site/blog/:friendly_identifier' => 'site/blog#show'
  match 'blog/:year/:month' => 'site/blog#index', :as => :blog_by_month_page, :year => /\d{4}/, :month => /\d{1,2}/
  match 'orders/:id/invoice' => 'site/orders#invoice', :as => :print_invoice
  match 'my-account' => 'site/customers#account', :as => :account
  match 'follow/:user_id' => 'site/customers#follow', :as => :follow
  match 'unfollow/:user_id' => 'site/customers#unfollow', :as => :unfollow
  match 'grape-guide' => 'site/grapes#index', :as => :grape_guide
  match 'request-new-password' => 'site/customers#request_new_password', :as => :request_new_password
  match 'wine-events' => 'site/categories#show', :as => :wine_events, :category => 'events'
  match 'wine-community' => 'site/forums#index', :as => :wine_community
  match 'grapes/search_results' => 'site/grapes#search_results'
  get '/landing.html'=> 'site/base#landing_page'
  get '/messages/send_reply'=> 'site/messages#send_reply'
  post '/messages/send_message' => 'site/messages#send_message'

  match 'cart/gift_options' => 'site/cart#gift_options'
  match 'checkouts/order_confirmation' => 'site/checkouts#order_confirmation'
  match 'cart/update_gift' => 'site/cart#update_gift'

  scope module: 'site' do  
      resources :products, :only => [:index, :show, :wine_of_the_week, :food_of_the_week] do
        resources :reviews, :only => [:new, :create]
        resources :wine_list, :only => [:index, :create, :destroy]
        resources :wish_list, :only => [:index, :create, :destroy]
        resources :cart, :only => [:create, :update, :destroy] do
          collection do
            get :empty
          end
        end
      end

    resources :forums do
      resources :topics do
        resources :posts
        resource :monitorship
      end
    end
    resources :authentications
    resources :search, :only => [:index] do
      collection do 
        get :find_wines
        get :find_other_drinks
        get :find_users
        get :find_producers
        get :find_hampers
        get :find_foods
        get :find_recipes
        get :find_wine_events
        get :find_grapes
        get :autocomplete_search_name
        get :autocomplete_search_wine_name
        get :autocomplete_search_food_name
        get :autocomplete_search_hamper_name
        get :autocomplete_search_drinks_name
        get :autocomplete_post_name
        get :autocomplete_search_recipes_name
      end
    end
    
  
    resources :orders, :only => [:index, :new, :create, :show] do
      member do
        get :cancel_review
      end
      match :download_pdf, :on => :collection
    end
    resources :wish_list, :only => [:index, :create, :destroy]
    resources :wine_lists, :only => [:index, :create, :destroy]
    resources :reviews
    resources :cart, :only => [:index, :update] do
      collection do
        get :empty
        get :continue_shopping
        get :user_select
        post :user_select
      end
    end
    resources :cart, :only => [:create, :update, :destroy] do
      get :autocomplete_user_name, :on => :collection
      collection do
        get :empty
        get "gift_options"
      end
    end
    resources :recipes do
      collection do
        get :recipes_list
      end
    end
    resources :reviews, :only => [:new, :create]
    resources :blog, :only => [:index, :show] do
      match :comment, :on => :member
    end

    resources :producers , :only => [:show, :index]
    resources :grapes, :only => [:index, :show]
    resources :faqs
    resources :customers do
      collection do
        get :account
        get :update_default_pic
        get :request_new_password
        post :find
        post :send_message
      end
    end
    resources :products, :only => [:show]
    resources :regions, :only => [:show, :index]
    resources :checkouts, :only => [:index] do
      collection do
        post :confirm_address
        get :payment
        get :paypal
        get :confirmed
      end
    end
    resources :news_letters, :only => [:show]
    resources :ship_addresses
    resources :chat do
      match :create_chat_user, :on => :collection
      match :send_data, :on => :collection
      match :send_message, :on => :collection, :via => :post
    end
    resources :sommelier
    resources :moods, :only => :index
  end

  match 'image' => 'site/images#show', :path_prefix => ':image_type'
  resources :image, :controller => 'site/images', :only => [:show], :path_prefix => ':image_type'

  resources :posts do
    collection do
      post :search
    end
  end

  resources :posts
  match 'admin/products/delete_products_of_the_week' => 'admin/products#delete_products_of_the_week'
  match 'admin/products/products_of_the_week' => 'admin/products#products_of_the_week'
  match '/show_order_details' => 'site/orders#show_order_details'
  match 'admin/products/products_sortby_quantity' => 'admin/products#products_sortby_quantity'
  match 'orders/review' => 'site/orders#review'
  match 'admin/xml' => 'admin/xml#index', :as => :xml

app/controllers/admin/forums_controller.rb
class Admin::ForumsController < ApplicationController
  before_filter :admin_login_required
  layout "admin"

  def index
    @forums = Forum.where("").order("name ASC").paginate(:page => params[:page], :per_page => 10)
    
    respond_to do |format|
      format.html
    end
  end
  
end

app/controllers/site/authentications_controller.rb
class Site::AuthenticationsController < ApplicationController
  def index
    @authentications = Authentication.all
  end

  def create
    omniauth = request.env["omniauth.auth"]
    authentication =
      if omniauth['provider'] == 'twitter'
        Authentication.find_by_provider_and_uid_and_token(omniauth['provider'], omniauth['uid'], omniauth['credentials']['token'])
      elsif omniauth['provider'] == 'facebook'
        Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
      end
    user = User.find_by_login(omniauth['info']['nickname'])
    session[:omniauth] = omniauth
    if authentication
      self.current_user = User.find(authentication.user_id)
      current_user.set_last_seen_at
      session[:current_user] = current_user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_url
    elsif omniauth['provider'].present? and user.present?
      flash[:notice] = "Please login"
      redirect_to "/login?login=#{user.login}&provider=#{omniauth['provider']}&uid=#{omniauth['uid']}&token=#{omniauth['credentials']['token']}"
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        redirect_to signup_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_path
  end
end

app/controllers/site/blog_controller.rb
 class Site::BlogController < ApplicationController
  layout "site"
  before_filter :store_comment, :only => :comment, :method => :post
#  before_filter :site_login_required, :only => :comment
  def index

    per_page = 25
    if params[:category] == 'search_blog_post'
      posts = Post.where("name like '%#{params[:text]}%' or friendly_identifier like '%#{params[:text]}%'")  
    elsif params[:tag_id]
      @tag = Tag.find(params[:tag_id])

       posts = @tag.posts.where(["blog_type_id = ?", 1]).order("created_at DESC").paginate(:page => params[:page], :per_page => per_page)

    elsif params[:year].blank? && params[:month].blank?
      posts = Post.where(["blog_type_id = ?", 1]).order("created_at DESC").paginate(:page => params[:page], :per_page => per_page)
    else
      @year = params[:year].to_i
      @month = params[:month].to_i
      begin_of_the_month = "1/#{@month}/#{@year}".to_time.utc
      end_of_the_month = begin_of_the_month.end_of_month.to_time.utc
     posts = Post.where("blog_type_id = ? AND created_at >= ? AND created_at <= ?", 1, begin_of_the_month.to_s(:db), end_of_the_month.to_s(:db)).paginate(:page => params[:page], :per_page => per_page)
    
    end
    @posts = posts
    
    respond_to do |wants|
      wants.html
      wants.xml { render :layout => false }
    end
  end

  def show
    store_location
    if params[:friendly_identifier]
      post = Post.find(params[:friendly_identifier])
    else
      post = Post.find(params[:id])
    end
    @post = post
    unless @post
      redirect_to "/404"
    else
      @post.count_view if @post
      @comments = @post.comments.where(reply_id: nil,public: true).paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
    end

  end

  def comment
    @post = Post.find(params[:id])
    comment_public = current_user ? current_user.admin? : false  
    @comment = Comment.new(
      :name => session[:name],
      :description => session[:description],
      :captcha => session[:captcha],
      :captcha_key => session[:captcha_key],
      :mail_check => session[:mail_check],
      :reply_id => session[:reply_id],
      :public => comment_public
    )
    @comment.post = @post if !session[:reply_id].present?
    @comment.email = current_user.email
    @comment.user_id = current_user.id
    if verify_recaptcha(model: @comment)  and @comment.save
      Notifier.comment(@comment,current_user).deliver
      flash[:notice] = "comment is successfully posted"
    elsif session[:reply_id].present?  and @comment.save
      Notifier.reply_comment(@comment,@comment.comment.user).deliver
      flash[:notice] = "comment is successfully posted"      
    else
      flash[:notice] = @comment.show_errors
     # render :action => :show
    end
      redirect_to blog_path(@post.friendly_identifier)
  end



  protected
  def store_comment

    if params[:comment]
      session[:name] = params[:comment][:name]
      session[:description] = params[:comment][:description]
      session[:captcha] = params[:comment][:captcha]
      session[:captcha_key] = params[:comment][:captcha_key]
      session[:mail_check] = params[:comment][:mail_check]
      session[:reply_id] = params[:comment][:reply_id]
    end
  end

  def check_mail_list(post, user)
    @post = Post.find(post)
    no_of_comment = @post.comments.count
    if no_of_comment == 1 
      return true
    else
      p no_of_comment

      @comments = (@post.comments).find(:all, :conditions =>[' mail_check = ?',true])
      p "********tyty***************************"
      p @comments.count
      p "**********ytyy**************************"
      for comment in @comments
        Notifier.comment(comment,user).deliver
      end
    end
  end

end

app/controllers/site/checkouts_controller.rb
class Site::CheckoutsController < ApplicationController



  before_filter :site_login_required
  before_filter :store_location
  after_filter :reset_session, :only => [:confirmed]


  #ssl_required :payment
  #ssl_required :all

  # UnComment this when site goes live
  # I think this is not working when the site is held as a sub domain of LegreenSolutions

  #Comment 2nd when we go Live
  #Now we are using this becuase https redirection is not working when site is sub domain of legreensolutions
    #ssl_allowed
    #ssl_required :all

    #ssl_allowed
    #ssl_required


  layout "site"

  def index
    unless @cart.valid?
      flash[:notice] = @cart.show_errors
      redirect_to cart_index_path
    end

    @ship_address = session[:ship_address] ||= current_user.default_ship_address
  end

  def confirm_address
    @ship_address = session[:ship_address] ||= current_user.ship_addresses.new(params[:ship_address])

    if @ship_address.valid?
       redirect_to payment_checkouts_path
    else
      flash[:notice] = @ship_address.show_errors
      redirect_to checkouts_path
   end
  end

  def payment
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @payment_method = 2 #set default payment method to credit card
  end

  def paypal
  end

  def confirmed
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @order = Order.find(:last,:conditions=>['user_id=?',current_user.id])
    @was_admin = false
    if session[:previous_admin_id]
      @was_admin = true
    end  
    revert_session
  end

  def order_confirmation
   if request.post?
    unless params[:accept].blank?
      redirect_to :controller=>'site/checkouts',:action=>'payment'
    else
      flash[:notice] = 'Please accept terms and conditions'
      #flash[:alert] = "Please accept terms and conditions"
      #redirect_to :controller=>'checkouts',:action=>'payment'
    end
   end
  end

  private
  def reset_session
    session[:ship_address] = nil
    session[:cart] = nil
  end
end

app/controllers/site/moods_controller.rb
class Site::MoodsController < ApplicationController

  layout "site"

  def index
    @moods = Mood.all
  end

end

app/views/site/forums/_form.html.erb
<p style="float:right; margin-top:0">
</p>

<p id="forum_name">

<table border="0" cellspacing="0" cellpadding="0" class="noborder nopad wide">
  <td>
    <label><%= 'Title' %></label><br />
    <%= form.text_field :name, :class => "primary" %>
  </td>
  <td style="text-align:right">
    <label><%= 'Position' %></label><br />
    <%= form.text_field :position, :size => 5 %>

  </td>
</table>

</p>
<p id="forum_descripion">
<label><%= 'Description'%></label><br />
<%= form.text_area :description, :rows => 7 %></p>

app/views/site/forums/_last_active_users.html.erb
<div class="border">
  <p>
    <strong>Last <%= @active_users.size%> Users active in forums</strong>
  </p>
  <ul type="none" style="padding:0;text-align:center;">
    <% @active_users.each do |user| %>
    <li style="float:left;margin-left:10px;">
      <%= link_to(avatar_for_user(user, "small"), customer_path(user)) %><br />
      <%= link_to(truncate(user.name, 10), customer_path(user), :style => "color:#003702;") %>
    </li>
    <% end %>
    <div style="clear:both"></div>
  </ul>
</div>

app/views/site/forums/_moderation.html.erb
<% unless @forum.description.blank? %>
  <%= @forum.description_html %>
  <hr />
  <% end %>
  <h5 style="margin-bottom:1.0em;"><%= 'Moderators' %></h5>

  <% unless @forum.moderators.empty? -%>
  <ul class="flat" style="margin-top:1em;">
  <% @forum.moderators.each do |user| -%>
    <li><%#= link_to user.display_name, user_path(user) %>
      <%= user.display_name %></li>
  <% end -%>
  </ul>
  <% else -%>
  <p><%= 'This forum is currently unmoderated.'%></p>
  <p><%= 'Please always be courteous.' %></p>
  <% end -%>

app/views/site/forums/_welcome_user.html.erb
<% if logged_in? %>
  <p>
    <strong>Welcome back</strong> <%=h current_user.name %>, <strong>Your last visit was:</strong> <%= time_ago_in_words(current_user.last_seen_at) %>
  </p>
<% end %>

app/views/site/forums/edit.html.erb
<div class="crumbs">
  <%= link_to 'Forums', forums_path %> <span class="arrow">&rarr;</span>
</div>

<h1><!-- Italian wine and food Online | Award winning wine merchant --><%= 'Edit Forum' %></h1>

<%= form_for :forum,
     :url  => forum_path(@forum),
     :html => { :method => :put } do |f| -%>
<%= render :partial => "form", :object => f %>
<%= submit_tag 'Save Forum' -%> or <%= link_to('Cancel', admin_forum_path) %>
<% end -%>

app/views/site/forums/new.html.erb
<h1><!-- Italian wine and food Online | Award winning wine merchant --><%= 'New Forum' %></h1>

<%= form_for :forum, :url => forums_path do |f| -%>
<%= render :partial => "form", :object => f %>
<%= submit_tag 'Create'-%> or <%= link_to('Cancel', admin_forums_path) -%>
<% end -%>

app/views/site/forums/show.html.erb
<%- set_title "Community-#{@forum.name}" -%>

<div id="wineBanner"><%= image_tag("forum-topics.jpg") %></div>
<br /><br />
<div style="margin:10px;" id="forum-container">
  <h1 style="text-align:center;font-size:20px;color:#666666;"><!-- Italian wine and food Online | Award winning wine merchant -->
  Forum</h1>
  <%= render :partial => "site/forums/welcome_user" %>
  <table cellspacing="0" cellpadding="0" width="100%">
    <tr>
      <td colspan="4" class="last">
        <p><strong>Italyabroad General Discussions</strong></p>
      </td>
    </tr>
    <tr>
      <td colspan="4" class="last">
        <p><strong style="color:#003702;"><%= @forum.name %></strong></p>
      </td>
    </tr>
    <tr>
      <td width="45%"><strong>Topic title</strong></td>
      <td width="15%"><strong>Replies</strong></td>
      <td width="20%"><strong>Topic Starter</strong></td>
      <td class="last"><strong>Last Action</strong></td>
    </tr>
    <% @topics.each_with_index do |topic, i|%>
    <tr <%= 'class="last"' if (i+1) == (@topics.size) %>>
      <td>
        <%= render :partial => "site/topics/topic_status", :locals => { :topic => topic} %>
        <%= topic_title_link(topic, :class => "entry-title", :rel => "bookmark" ) %>
      </td>
      <td><%= topic.posts_count %></td>
      <td><%=h topic.user.name %></td>
      <td class="last"><%= time_ago_in_words(topic.replied_at) %></td>
    </tr>
    <% end %>
  </table>
  <% if logged_in? %>
    <p><%= link_to 'Add New topic', new_forum_topic_path(@forum), :class => "utility" %></p>
  <% end%>
  <div class="digg_pagination pagination-2 clearfix">
    <div class="page_info show-result">
      <%= page_entries_info @topics %>
    </div>
    <div class="pagination-links">
      <%= will_paginate @topics, :container => false %>
    </div>
  </div>
    
  <%= render :partial => "site/forums/last_active_users" %>
</div>


<% content_for :right do %>
  <%#= render :partial => '/site/shared/box_products_on_offer' %>
  <%= render :partial => '/site/shared/box_wine_tours' %>
  <%= render :partial => '/site/shared/box_grape_guide' %>
  <br />
  <%= render :partial => '/site/shared/box_subscriptions' %>
  <br />
  <%= render :partial => '/site/shared/social_follow' %>
<% end %>