config/routes.rb
ItalyabroadNew::Application.routes.draw do
  namespace :admin do
    resources :testimonials
    resources :faqs
    resources :shipping_agencies
    resources :occasions
    resources :about_us
    resources :contact_messages
    resources :regions do
      resources :images, :only => [:destroy]
    end
    resources :producers  do
      resources :images, :only => [:destroy]
    end
    resources :grapes do
      resources :images, :only => [:destroy]
    end
    resources :forums
    resources :categories
    resources :deliveries
    resources :cupons do
      match :product_list, :on => :collection
    end
    resources :forums
    resources :posts
    resources :comments
    resources :reviews do
      match :send_mails, :on => :collection
    end
    resources :orders, :only => [:index, :show, :destroy] do
      member do
        get :print_tasting
        get :print_invoice
        get :print_picking_list
        get :delivery_details
        get :cancel_delivery_charge
      end
    end
    resources :users
    resources :customers do
      collection do
        get :print_user_details
      end
    end
    resources :gift_options
    resources :subscriptions
    resources :news_letters do
      resources :images, :only => [:destroy]
    end
    resources :recipes do
      collection do 
        get 'xml'
      end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :resources, :only => [:destroy]
    resources :images, :only => [:destroy]
    resources :products do
       collection do 
          get 'xml'
        end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :settings, :only => [:index, :update] do
      
      collection do 
        get 'available_backups'
        get 'restore'
        get 'take_backup_now'
        get 'download'

      end

      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :small_box_settings 
    get "moods/index"

    get "moods/new"

    post "moods/create"

    get "moods/edit"

    put "moods/update"
    delete "moods/destroy"
  end

  get "moods/index"

  resources :chat_messages do
    collection do
      get "show_alert"
      get "take_username" => "chat_messages#take_username"
    end
  end

  namespace(:admin){
    resources :wine_sizes
    resources :sommeliers
    resources :food_or_drinks
    resources :desired_expenditures
    resources :food_options
    resources :manage_sommeliers, :only => [:index, :create]
  }

  match "/auth/:provider/callback" => "site/authentications#create"

  match 'suppliers' => 'site/base#supplier', :as => :meet_us
  match 'contact-us' => 'site/base#contact', :as => :contact_us
  match 'corporate-services' => 'site/base#corporate', :as => :corporate
  match 'wholesale-enquiry' => 'site/base#enquiries', :as => :wholesale_enquiry
  match 'olive-oil-guide' => 'site/base#olive_oil_guide', :as => :olive_oil_guide
  match 'about-us' => 'site/base#about_us', :as => :about_us
  match 'our-manifesto' => 'site/base#our_principles', :as => :our_principles
  match 'meet-us' => 'site/base#meet_us', :as => :meet_us
  match 'terms-and-conditions' => 'site/base#conditions', :as => :terms_and_conditions
  match 'privacy-policy' => 'site/base#privacy', :as => :privacy_policy
  match 'delivery-services' => 'site/base#delivery_services', :as => :delivery_services
  match 'managing-account' => 'site/base#managing_account', :as => :managing_account
  match 'contact-details' => 'site/base#contact_details', :as => :contact_details
  match 'sitemap' => 'site/base#sitemap', :as => :sitemap
  match 'google_sitemap.xml' => 'site/base#google_sitemap', :defaults => {:format => :xml}
  match 'guarantee_of_satisfaction' => 'site/base#guarantee_of_satisfaction', :as => :guarantee_of_satisfaction
  match 'enable_disable_chat' => 'admin/base#enable_disable_chat', :as => :enable_disable_chat
  match 'testimonial' => 'site/testimonials#index', :as => :testimonial
  match 'popular' => 'site/base#popular', :as => :popular
  match 'signup' => 'site/customers#new', :as => :signup
  match 'login' => 'site/base#login', :as => :login
  match 'guest_login' => 'site/base#guest_login', :as => :guest_login
  match 'logout' => 'site/base#logout', :as => :logout
  match 'subscribe-dali-news' => 'site/base#subscribe', :as => :subscribe_dali_news
  match 'subscriptions' => 'site/base#create_subscription', :as => :create_subscription, :method => :post
  match 'thank-you' => 'site/base#subscription_complete', :as => :subscription_complete
  match 'unsubscribe-dali-news' => 'site/base#unsubscribe', :as => :unsubscribe_dali_news
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  match 'siteadmin' => 'admin/base#index', :as => :siteadmin
  match 'admin/login' => 'admin/base#login', :as => :admin_login
  get '/site/blog/:friendly_identifier' => 'site/blog#show'
  match 'blog/:year/:month' => 'site/blog#index', :as => :blog_by_month_page, :year => /\d{4}/, :month => /\d{1,2}/
  match 'orders/:id/invoice' => 'site/orders#invoice', :as => :print_invoice
  match 'my-account' => 'site/customers#account', :as => :account
  match 'follow/:user_id' => 'site/customers#follow', :as => :follow
  match 'unfollow/:user_id' => 'site/customers#unfollow', :as => :unfollow
  match 'grape-guide' => 'site/grapes#index', :as => :grape_guide
  match 'request-new-password' => 'site/customers#request_new_password', :as => :request_new_password
  match 'wine-events' => 'site/categories#show', :as => :wine_events, :category => 'events'
  match 'wine-community' => 'site/forums#index', :as => :wine_community
  match 'grapes/search_results' => 'site/grapes#search_results'
  get '/landing.html'=> 'site/base#landing_page'
  get '/messages/send_reply'=> 'site/messages#send_reply'
  post '/messages/send_message' => 'site/messages#send_message'

  match 'cart/gift_options' => 'site/cart#gift_options'
  match 'checkouts/order_confirmation' => 'site/checkouts#order_confirmation'
  match 'cart/update_gift' => 'site/cart#update_gift'

  scope module: 'site' do  
      resources :products, :only => [:index, :show, :wine_of_the_week, :food_of_the_week] do
        resources :reviews, :only => [:new, :create]
        resources :wine_list, :only => [:index, :create, :destroy]
        resources :wish_list, :only => [:index, :create, :destroy]
        resources :cart, :only => [:create, :update, :destroy] do
          collection do
            get :empty
          end
        end
      end

    resources :forums do
      resources :topics do
        resources :posts
        resource :monitorship
      end
    end
    resources :authentications
    resources :search, :only => [:index] do
      collection do 
        get :find_wines
        get :find_other_drinks
        get :find_users
        get :find_producers
        get :find_hampers
        get :find_foods
        get :find_recipes
        get :find_wine_events
        get :find_grapes
        get :autocomplete_search_name
        get :autocomplete_search_wine_name
        get :autocomplete_search_food_name
        get :autocomplete_search_hamper_name
        get :autocomplete_search_drinks_name
        get :autocomplete_post_name
        get :autocomplete_search_recipes_name
      end
    end
    
  
    resources :orders, :only => [:index, :new, :create, :show] do
      member do
        get :cancel_review
      end
      match :download_pdf, :on => :collection
    end
    resources :wish_list, :only => [:index, :create, :destroy]
    resources :wine_lists, :only => [:index, :create, :destroy]
    resources :reviews
    resources :cart, :only => [:index, :update] do
      collection do
        get :empty
        get :continue_shopping
        get :user_select
        post :user_select
      end
    end
    resources :cart, :only => [:create, :update, :destroy] do
      get :autocomplete_user_name, :on => :collection
      collection do
        get :empty
        get "gift_options"
      end
    end
    resources :recipes do
      collection do
        get :recipes_list
      end
    end
    resources :reviews, :only => [:new, :create]
    resources :blog, :only => [:index, :show] do
      match :comment, :on => :member
    end

    resources :producers , :only => [:show, :index]
    resources :grapes, :only => [:index, :show]
    resources :faqs
    resources :customers do
      collection do
        get :account
        get :update_default_pic
        get :request_new_password
        post :find
        post :send_message
      end
    end
    resources :products, :only => [:show]
    resources :regions, :only => [:show, :index]
    resources :checkouts, :only => [:index] do
      collection do
        post :confirm_address
        get :payment
        get :paypal
        get :confirmed
      end
    end
    resources :news_letters, :only => [:show]
    resources :ship_addresses
    resources :chat do
      match :create_chat_user, :on => :collection
      match :send_data, :on => :collection
      match :send_message, :on => :collection, :via => :post
    end
    resources :sommelier
    resources :moods, :only => :index
  end

  match 'image' => 'site/images#show', :path_prefix => ':image_type'
  resources :image, :controller => 'site/images', :only => [:show], :path_prefix => ':image_type'

  resources :posts do
    collection do
      post :search
    end
  end

  resources :posts
  match 'admin/products/delete_products_of_the_week' => 'admin/products#delete_products_of_the_week'
  match 'admin/products/products_of_the_week' => 'admin/products#products_of_the_week'
  match '/show_order_details' => 'site/orders#show_order_details'
  match 'admin/products/products_sortby_quantity' => 'admin/products#products_sortby_quantity'
  match 'orders/review' => 'site/orders#review'
  match 'admin/xml' => 'admin/xml#index', :as => :xml

app/controllers/site/authentications_controller.rb
class Site::AuthenticationsController < ApplicationController
  def index
    @authentications = Authentication.all
  end

  def create
    omniauth = request.env["omniauth.auth"]
    authentication =
      if omniauth['provider'] == 'twitter'
        Authentication.find_by_provider_and_uid_and_token(omniauth['provider'], omniauth['uid'], omniauth['credentials']['token'])
      elsif omniauth['provider'] == 'facebook'
        Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
      end
    user = User.find_by_login(omniauth['info']['nickname'])
    session[:omniauth] = omniauth
    if authentication
      self.current_user = User.find(authentication.user_id)
      current_user.set_last_seen_at
      session[:current_user] = current_user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_url
    elsif omniauth['provider'].present? and user.present?
      flash[:notice] = "Please login"
      redirect_to "/login?login=#{user.login}&provider=#{omniauth['provider']}&uid=#{omniauth['uid']}&token=#{omniauth['credentials']['token']}"
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        redirect_to signup_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_path
  end
end

app/controllers/site/blog_controller.rb
 class Site::BlogController < ApplicationController
  layout "site"
  before_filter :store_comment, :only => :comment, :method => :post
#  before_filter :site_login_required, :only => :comment
  def index

    per_page = 25
    if params[:category] == 'search_blog_post'
      posts = Post.where("name like '%#{params[:text]}%' or friendly_identifier like '%#{params[:text]}%'")  
    elsif params[:tag_id]
      @tag = Tag.find(params[:tag_id])

       posts = @tag.posts.where(["blog_type_id = ?", 1]).order("created_at DESC").paginate(:page => params[:page], :per_page => per_page)

    elsif params[:year].blank? && params[:month].blank?
      posts = Post.where(["blog_type_id = ?", 1]).order("created_at DESC").paginate(:page => params[:page], :per_page => per_page)
    else
      @year = params[:year].to_i
      @month = params[:month].to_i
      begin_of_the_month = "1/#{@month}/#{@year}".to_time.utc
      end_of_the_month = begin_of_the_month.end_of_month.to_time.utc
     posts = Post.where("blog_type_id = ? AND created_at >= ? AND created_at <= ?", 1, begin_of_the_month.to_s(:db), end_of_the_month.to_s(:db)).paginate(:page => params[:page], :per_page => per_page)
    
    end
    @posts = posts
    
    respond_to do |wants|
      wants.html
      wants.xml { render :layout => false }
    end
  end

  def show
    store_location
    if params[:friendly_identifier]
      post = Post.find(params[:friendly_identifier])
    else
      post = Post.find(params[:id])
    end
    @post = post
    unless @post
      redirect_to "/404"
    else
      @post.count_view if @post
      @comments = @post.comments.where(reply_id: nil,public: true).paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
    end

  end

  def comment
    @post = Post.find(params[:id])
    comment_public = current_user ? current_user.admin? : false  
    @comment = Comment.new(
      :name => session[:name],
      :description => session[:description],
      :captcha => session[:captcha],
      :captcha_key => session[:captcha_key],
      :mail_check => session[:mail_check],
      :reply_id => session[:reply_id],
      :public => comment_public
    )
    @comment.post = @post if !session[:reply_id].present?
    @comment.email = current_user.email
    @comment.user_id = current_user.id
    if verify_recaptcha(model: @comment)  and @comment.save
      Notifier.comment(@comment,current_user).deliver
      flash[:notice] = "comment is successfully posted"
    elsif session[:reply_id].present?  and @comment.save
      Notifier.reply_comment(@comment,@comment.comment.user).deliver
      flash[:notice] = "comment is successfully posted"      
    else
      flash[:notice] = @comment.show_errors
     # render :action => :show
    end
      redirect_to blog_path(@post.friendly_identifier)
  end



  protected
  def store_comment

    if params[:comment]
      session[:name] = params[:comment][:name]
      session[:description] = params[:comment][:description]
      session[:captcha] = params[:comment][:captcha]
      session[:captcha_key] = params[:comment][:captcha_key]
      session[:mail_check] = params[:comment][:mail_check]
      session[:reply_id] = params[:comment][:reply_id]
    end
  end

  def check_mail_list(post, user)
    @post = Post.find(post)
    no_of_comment = @post.comments.count
    if no_of_comment == 1 
      return true
    else
      p no_of_comment

      @comments = (@post.comments).find(:all, :conditions =>[' mail_check = ?',true])
      p "********tyty***************************"
      p @comments.count
      p "**********ytyy**************************"
      for comment in @comments
        Notifier.comment(comment,user).deliver
      end
    end
  end

end

app/controllers/site/checkouts_controller.rb
class Site::CheckoutsController < ApplicationController



  before_filter :site_login_required
  before_filter :store_location
  after_filter :reset_session, :only => [:confirmed]


  #ssl_required :payment
  #ssl_required :all

  # UnComment this when site goes live
  # I think this is not working when the site is held as a sub domain of LegreenSolutions

  #Comment 2nd when we go Live
  #Now we are using this becuase https redirection is not working when site is sub domain of legreensolutions
    #ssl_allowed
    #ssl_required :all

    #ssl_allowed
    #ssl_required


  layout "site"

  def index
    unless @cart.valid?
      flash[:notice] = @cart.show_errors
      redirect_to cart_index_path
    end

    @ship_address = session[:ship_address] ||= current_user.default_ship_address
  end

  def confirm_address
    @ship_address = session[:ship_address] ||= current_user.ship_addresses.new(params[:ship_address])

    if @ship_address.valid?
       redirect_to payment_checkouts_path
    else
      flash[:notice] = @ship_address.show_errors
      redirect_to checkouts_path
   end
  end

  def payment
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @payment_method = 2 #set default payment method to credit card
  end

  def paypal
  end

  def confirmed
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @order = Order.find(:last,:conditions=>['user_id=?',current_user.id])
    @was_admin = false
    if session[:previous_admin_id]
      @was_admin = true
    end  
    revert_session
  end

  def order_confirmation
   if request.post?
    unless params[:accept].blank?
      redirect_to :controller=>'site/checkouts',:action=>'payment'
    else
      flash[:notice] = 'Please accept terms and conditions'
      #flash[:alert] = "Please accept terms and conditions"
      #redirect_to :controller=>'checkouts',:action=>'payment'
    end
   end
  end

  private
  def reset_session
    session[:ship_address] = nil
    session[:cart] = nil
  end
end

app/controllers/site/comments_controller.rb
class Site::CommentsController < ApplicationController
  before_filter :site_login_required
  def index
    @comments = Comment.where(['user_id =?',params[:id]]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html { render :layout => 'site' }
    end
  end
end

app/controllers/site/moods_controller.rb
class Site::MoodsController < ApplicationController

  layout "site"

  def index
    @moods = Mood.all
  end

end

app/views/site/templates/_product_without_category.html.erb
<div id="header"><%= @product.name %> <%= "(" + @product.size + ")" unless @product.size.blank? %></div>
<table class="product_info">
  <tr>
    <td class="image" style ="padding:0 10px 0 0">
      <% if !(@product.image_1).blank? %>
          <%#= show_image_tag('product', @product.image_1, :jpg) %>
          <%= link_to show_image_tag('product', @product.image_1, :jpg,@product.name), image_url('product_display', @product.image_1, :jpg),{:rel => "lightbox", :title => @product.name}  %>
      <% else %>

          <%= image_tag("no_images/product_wine.jpg",:size => "230x250",:alt=>@product.name) %>

      <% end %>
    </td>
    <td class="properties" valign="top">

      <%# if @product.categories.root.name.downcase == "food" || @product.categories.root.name.downcase == "hampers" || @product.categories.root.name.downcase == "wine" %>
      <table>
        <tr>
          <td>Avg.Rating:</td>
          <td class="data">
            <%= show_ratings(@product, @product.average_rating_round).html_safe() %>
          </td>
        </tr>

        <%- if @product.is_wine? || @product.is_food? -%>
            <tr>
              <td valign="top">Region:</td>
              <td class="data">
                <% if @product.region %>
                    <% if @product.region.active %>
                        <%= link_to(@product.region.name, region_path(@product.region))   %>
                    <% else %>
                        "No region"
                    <% end %>
                <% else %>
                    "No region"
                <% end %>
              </td>
            </tr>
        <%- end -%>
        <%- if @product.is_wine? -%>
            <tr>
              <td valign="top">Grape:</td>
              <td class="data user_name_class">
                <%= @product.grapes.collect{ |g| [link_to(g.name, grape_path(g))] }.join(", ") %>
              </td>
            </tr>
        <%- end -%>
        <tr>
          <td valign="top">Producer:</td>
          <td class="data">
            <% if @product.producer
                 if @product.producer.active %>
                    <%= link_to(@product.producer.name, producer_path(@product.producer)) %>
                <% else %>
                    No producer
                <% end %>
            <% else %>
                No producer
            <% end %>
          </td>
        </tr>
        <%- if @product.is_wine? -%>
            <tr>
              <td valign="top">Vintage:</td>
              <td class="data"><%= @product.vintage %></td>
            </tr>
            <tr>
              <td valign="top">Volume:</td>
              <td class="data"><%= @product.volume %></td>
            </tr>
        <%- end  -%>
        <tr>
          <td valign="top">Vegan:</td>
          <td class="data"><%= @product.vegetarian ? "YES" : "NO" %></td>
        </tr>
        <tr>
          <td valign="top">Organic:</td>
          <td class="data"><%= @product.organic ? "YES" : "NO" %></td>
        </tr>
      </table>
      <%# end%>

      <br /><br />
      <%= render :partial => '/site/shared/social_bookmarks' %>
    </td>
    <td>
      <div class="box_price_product">
        <ul>
          <li class="price_info">
            <% if @product.discount.to_i > 0 %>
                <div style="font-size:14px;color:#003300;">Was <span style="text-decoration: line-through;"><%= number_to_currency @product.price, :unit => "£" %></span></div>
                <span class="price red" style="color:#003300;">Now&nbsp;<span class="red-text"><%= number_to_currency @product.price_discounted.first, :unit => "£" %></span></span>
                (save <span style="color:red;"><%= number_to_currency (@product.price * @product.discount.to_f / 100), :unit => "£" %></span>)
            <% else %>
                <span class="price" style="color:#003300;"><%= number_to_currency @product.price, :unit => "£" %></span>
            <% end %>
          </li>
          <% if @product.from_quantity > 0 && @product.from_quantity_price > 0 %>
              <li>
                <%# if @product.categories.root.name == "Wine" %>
                <span style="color:red;">Buy a case of <%= @product.from_quantity %> and save <span><%= number_to_currency @product.from_quantity_price, :unit => "£" %><br/>(price per bottle <%= number_to_currency @product.price_per_bottle, :unit => "£" %>)</span></span>
                <%# elsif @product.categories.root.name == "Food" %>
                <span style="color:red;">Buy <%= @product.from_quantity %> and save <span><%= number_to_currency @product.from_quantity_price, :unit => "£" %></span></span>
                <%# end %>
              </li>
          <% end %>
          <li class="cart_form">
            <%- if @product.out_of_stock? -%>
                <%= image_tag('out_of_stock.png') %>
            <%- else -%>
                <%= form_for(:cart, :url => product_cart_index_path(@product), :remote => true) do  -%>
                    Qty: <%#= select :cart, :quantity, [1,2,3,4,5,6,7,8,9] %>
                    <%= text_field :cart, :quantity,:value=> 1, :size => '4' %><br /><br />
                    <%= image_submit_tag("buttons/add_to_cart_button.png") %>
                <%- end -%>
            <%- end -%>
            <%= link_to(image_tag("add_to_wish_list.png"), "/wish_list?product_id=#{@product.id}", :remote => true, :method => :post) %>
            <%# if  @product.categories.root.name.downcase == 'wine' %>
            <%#= link_to_remote image_tag("WINE_LIST.jpg"), :url => product_wine_list_index_path(@product), :html => {:style => "color:#464646;", :method => :post} %>
            <%# end %>
          </li>
        </ul>
      </div>
    </td>
  </tr>

</table>

<div style="clear:both;"></div>
<div id="wineDesc">
  <br />
  <h3>Description</h3>
  <%= @product.description.gsub("\n","<br />").html_safe rescue "Product has no description" %>
</div>

<!--<div style="float: left;" id ="other-image"></div>

<div style="font:normal 16px Arial;padding:0 0 0 10px"><%#= link_to_remote(("Other images"),:url => { :controller => "site/categories",:action => "all_mixedcase_image", :parent =>@product.categories.root.name }) %></div>
-->

<div id="wineProducer">
  <br />
  <h3>Producer</h3>
  <% if @product.producer %>
      <% if @product.producer.active %>
          <%= @product.producer.description.gsub("\n","<br />") %>
      <% else %>
          "Product has no producer description"
      <% end %>
  <% else %>
      "Product has no producer description"
  <% end %>
</div>
<div id="wineReview">
  <br />
  <h3>Reviews <%= link_to("(Add Review)", login_path, :style => "font-size:12px;") unless logged_in?  %></h3>
  <%= render :partial => 'site/shared/review_view_short', :locals => {:reviewer => @product} %>
  <div style="clear:both;"></div>
  <%- if logged_in? -%>
      <h3>Leave your review</h3>
      <%= render(:partial => 'site/reviews/new', :locals => {:create_url => product_reviews_path(@product, :return_to => nested_products_uri(@product))}) %>
  <%- end -%>
</div>
<%- related_products = @product.correlations.all(:limit => 5) -%>
<%- column_width = related_products.size -%>
<% unless related_products.blank? %>
    <div id="wineRelated">
      <h3>People who bought this also bought..</h3>
      <ul>
        <% for related_product in related_products %>
            <li style="width:<%= 100/column_width %>%;text-align:center">
              <table>
                <tr>
                  <td style="height:150px;vertical-align:bottom"><%= link_to show_image_tag(related_product.layout_image, related_product.image_1, :jpg,related_product.name), nested_products_uri(related_product) %></td>
                </tr>
                <tr>
                  <td><%= link_to related_product.name, nested_products_uri(related_product) %></td>
                </tr>
                <tr>
                  <td><%= number_to_currency related_product.price, :unit => "£" %></td>
                </tr>
                <tr>
                  <td>
                    <%= link_to(image_tag("buttons/add_to_cart_button.png"), "/cart?product_id=#{@product.id}", :remote => true, :method => :post) %>
                  </td>
                </tr>
              </table>
            </li>
        <% end %>
      </ul>
    </div>
<% end %>
<% content_for :right do %>
    <%= render :partial => "/site/shared/box_wine_search" %>
    <br />
    <%= render :partial => '/site/shared/box_suggested_wines' %>
    <br />
    <%= render :partial => '/site/shared/box_event' %>
    <br />
   	<%= render :partial => '/site/shared/box_mood' %>
    <br />
    <%= render :partial => '/site/shared/social_follow' %>

<% end %>

app/views/site/templates/_wine_club_card.html.erb
<%- @class = "wine_club"; @breadcrumbs = "#{link_to("Home", root_url, :title=>"Home")} &raquo; #{link_to("Wine club", "/wine-club", :title=>"Wine Club")} &raquo; #{@product.name + '...'}" -%>
<% if @product.image_1  %>
<div id="wineBanner" class="main-banner"><%= image_tag(image_url("product_wine_club", @product.image_1, :jpg),:alt=>@product.name, :title=>@product.name)  %></div>
<% else %>
  <div class="main-banner"><img src="/images/wine-club-banner.png" alt="Wine club banner" title="Wine club banner" /></div>
<% end %>
<div class="row">
  <div class="two-colum-row clearfix">
    <div class="col-md-3 left-side-bar">
      <%= render :partial=> '/site/shared/box_wine_club_testimonials' %>
    </div>
    <div class="col-md-9">
      <!-- start wine detail wrapper-->
      <div class="wine-detail-wrapper">
        <div class="green-heading-with-border">
          <h1><!-- Italian wine and food Online | Award winning wine merchant -->
          <%= @product.name %></h1>
        </div>
        <div class="bottom-50"><%= @product.description.gsub("\n","<br />").html_safe rescue "Product has no description" %>
          <div class="row clearfix">
         <%= render :partial => 'site/templates/events_product_add_cart',locals: { ticket: false} %>
      
             <%= render :partial => 'site/templates/invite_a_friend'%>
        <!-- < % unless logged_in? %> -->
          <!-- <div class="green-heading-with-border">
            Reviews <%= link_to("(Add Review)", login_path, :title=>"Add Review") %>
          </div> -->
        <!-- < % end %> -->
          
        
        <%- if logged_in? -%>
          <div class="green-heading-with-border">Leave your review <%= link_to '(Add Review)',"#",:onclick=>"document.getElementById('add_review').style.display='block';return false;", :title=>"Add Review" %></div>
          <div id="add_review" style="display:none;">
            <div class="latest-review-box bottom-50">
              <%= render(:partial => 'site/reviews/new', :locals => {:product_id=>@product.id  ,:create_url => reviews_path(@product, :return_to => nested_products_uri(@product))}) %>
          </div>
        </div>
          <div class="latest-review-box bottom-50">
              <%= render :partial => 'site/shared/review_view_short', :locals => {:reviewer => @product} %>
            </div>
        <%- end -%>
      </div><!-- end wine detail wrapper-->
    </div>
  </div>
</div>
<!-- start 3 colum  boxes-->
<div class="community-row clearfix ">
  <%= render :partial => '/site/shared/our_community' %>
  <%= render :partial => '/site/shared/wine_club' %>
  <%= render :partial => '/site/shared/cercavino' %>
</div><!-- start 3 colum  boxes-->