config/routes.rb
ItalyabroadNew::Application.routes.draw do
  namespace :admin do
    resources :testimonials
    resources :faqs
    resources :shipping_agencies
    resources :occasions
    resources :about_us
    resources :contact_messages
    resources :regions do
      resources :images, :only => [:destroy]
    end
    resources :producers  do
      resources :images, :only => [:destroy]
    end
    resources :grapes do
      resources :images, :only => [:destroy]
    end
    resources :forums
    resources :categories
    resources :deliveries
    resources :cupons do
      match :product_list, :on => :collection
    end
    resources :forums
    resources :posts
    resources :comments
    resources :reviews do
      match :send_mails, :on => :collection
    end
    resources :orders, :only => [:index, :show, :destroy] do
      member do
        get :print_tasting
        get :print_invoice
        get :print_picking_list
        get :delivery_details
        get :cancel_delivery_charge
      end
    end
    resources :users
    resources :customers do
      collection do
        get :print_user_details
      end
    end
    resources :gift_options
    resources :subscriptions
    resources :news_letters do
      resources :images, :only => [:destroy]
    end
    resources :recipes do
      collection do 
        get 'xml'
      end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :resources, :only => [:destroy]
    resources :images, :only => [:destroy]
    resources :products do
       collection do 
          get 'xml'
        end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :settings, :only => [:index, :update] do
      
      collection do 
        get 'available_backups'
        get 'restore'
        get 'take_backup_now'
        get 'download'

      end

      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :small_box_settings 
    get "moods/index"

    get "moods/new"

    post "moods/create"

    get "moods/edit"

    put "moods/update"
    delete "moods/destroy"
  end

  get "moods/index"

  resources :chat_messages do
    collection do
      get "show_alert"
      get "take_username" => "chat_messages#take_username"
    end
  end

  namespace(:admin){
    resources :wine_sizes
    resources :sommeliers
    resources :food_or_drinks
    resources :desired_expenditures
    resources :food_options
    resources :manage_sommeliers, :only => [:index, :create]
  }

  match "/auth/:provider/callback" => "site/authentications#create"

  match 'suppliers' => 'site/base#supplier', :as => :meet_us
  match 'contact-us' => 'site/base#contact', :as => :contact_us
  match 'corporate-services' => 'site/base#corporate', :as => :corporate
  match 'wholesale-enquiry' => 'site/base#enquiries', :as => :wholesale_enquiry
  match 'olive-oil-guide' => 'site/base#olive_oil_guide', :as => :olive_oil_guide
  match 'about-us' => 'site/base#about_us', :as => :about_us
  match 'our-manifesto' => 'site/base#our_principles', :as => :our_principles
  match 'meet-us' => 'site/base#meet_us', :as => :meet_us
  match 'terms-and-conditions' => 'site/base#conditions', :as => :terms_and_conditions
  match 'privacy-policy' => 'site/base#privacy', :as => :privacy_policy
  match 'delivery-services' => 'site/base#delivery_services', :as => :delivery_services
  match 'managing-account' => 'site/base#managing_account', :as => :managing_account
  match 'contact-details' => 'site/base#contact_details', :as => :contact_details
  match 'sitemap' => 'site/base#sitemap', :as => :sitemap
  match 'google_sitemap.xml' => 'site/base#google_sitemap', :defaults => {:format => :xml}
  match 'guarantee_of_satisfaction' => 'site/base#guarantee_of_satisfaction', :as => :guarantee_of_satisfaction
  match 'enable_disable_chat' => 'admin/base#enable_disable_chat', :as => :enable_disable_chat
  match 'testimonial' => 'site/testimonials#index', :as => :testimonial
  match 'popular' => 'site/base#popular', :as => :popular
  match 'signup' => 'site/customers#new', :as => :signup
  match 'login' => 'site/base#login', :as => :login
  match 'guest_login' => 'site/base#guest_login', :as => :guest_login
  match 'logout' => 'site/base#logout', :as => :logout
  match 'subscribe-dali-news' => 'site/base#subscribe', :as => :subscribe_dali_news
  match 'subscriptions' => 'site/base#create_subscription', :as => :create_subscription, :method => :post
  match 'thank-you' => 'site/base#subscription_complete', :as => :subscription_complete
  match 'unsubscribe-dali-news' => 'site/base#unsubscribe', :as => :unsubscribe_dali_news
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  match 'siteadmin' => 'admin/base#index', :as => :siteadmin
  match 'admin/login' => 'admin/base#login', :as => :admin_login
  get '/site/blog/:friendly_identifier' => 'site/blog#show'
  match 'blog/:year/:month' => 'site/blog#index', :as => :blog_by_month_page, :year => /\d{4}/, :month => /\d{1,2}/
  match 'orders/:id/invoice' => 'site/orders#invoice', :as => :print_invoice
  match 'my-account' => 'site/customers#account', :as => :account
  match 'follow/:user_id' => 'site/customers#follow', :as => :follow
  match 'unfollow/:user_id' => 'site/customers#unfollow', :as => :unfollow
  match 'grape-guide' => 'site/grapes#index', :as => :grape_guide
  match 'request-new-password' => 'site/customers#request_new_password', :as => :request_new_password
  match 'wine-events' => 'site/categories#show', :as => :wine_events, :category => 'events'
  match 'wine-community' => 'site/forums#index', :as => :wine_community
  match 'grapes/search_results' => 'site/grapes#search_results'
  get '/landing.html'=> 'site/base#landing_page'
  get '/messages/send_reply'=> 'site/messages#send_reply'
  post '/messages/send_message' => 'site/messages#send_message'

  match 'cart/gift_options' => 'site/cart#gift_options'
  match 'checkouts/order_confirmation' => 'site/checkouts#order_confirmation'
  match 'cart/update_gift' => 'site/cart#update_gift'

  scope module: 'site' do  
      resources :products, :only => [:index, :show, :wine_of_the_week, :food_of_the_week] do
        resources :reviews, :only => [:new, :create]
        resources :wine_list, :only => [:index, :create, :destroy]
        resources :wish_list, :only => [:index, :create, :destroy]
        resources :cart, :only => [:create, :update, :destroy] do
          collection do
            get :empty
          end
        end
      end

    resources :forums do
      resources :topics do
        resources :posts
        resource :monitorship
      end
    end
    resources :authentications
    resources :search, :only => [:index] do
      collection do 
        get :find_wines
        get :find_other_drinks
        get :find_users
        get :find_producers
        get :find_hampers
        get :find_foods
        get :find_recipes
        get :find_wine_events
        get :find_grapes
        get :autocomplete_search_name
        get :autocomplete_search_wine_name
        get :autocomplete_search_food_name
        get :autocomplete_search_hamper_name
        get :autocomplete_search_drinks_name
        get :autocomplete_post_name
        get :autocomplete_search_recipes_name
      end
    end
    
  
    resources :orders, :only => [:index, :new, :create, :show] do
      member do
        get :cancel_review
      end
      match :download_pdf, :on => :collection
    end
    resources :wish_list, :only => [:index, :create, :destroy]
    resources :wine_lists, :only => [:index, :create, :destroy]
    resources :reviews
    resources :cart, :only => [:index, :update] do
      collection do
        get :empty
        get :continue_shopping
        get :user_select
        post :user_select
      end
    end
    resources :cart, :only => [:create, :update, :destroy] do
      get :autocomplete_user_name, :on => :collection
      collection do
        get :empty
        get "gift_options"
      end
    end
    resources :recipes do
      collection do
        get :recipes_list
      end
    end
    resources :reviews, :only => [:new, :create]
    resources :blog, :only => [:index, :show] do
      match :comment, :on => :member
    end

    resources :producers , :only => [:show, :index]
    resources :grapes, :only => [:index, :show]
    resources :faqs
    resources :customers do
      collection do
        get :account
        get :update_default_pic
        get :request_new_password
        post :find
        post :send_message
      end
    end
    resources :products, :only => [:show]
    resources :regions, :only => [:show, :index]
    resources :checkouts, :only => [:index] do
      collection do
        post :confirm_address
        get :payment
        get :paypal
        get :confirmed
      end
    end
    resources :news_letters, :only => [:show]
    resources :ship_addresses
    resources :chat do
      match :create_chat_user, :on => :collection
      match :send_data, :on => :collection
      match :send_message, :on => :collection, :via => :post
    end
    resources :sommelier
    resources :moods, :only => :index
  end

  match 'image' => 'site/images#show', :path_prefix => ':image_type'
  resources :image, :controller => 'site/images', :only => [:show], :path_prefix => ':image_type'

  resources :posts do
    collection do
      post :search
    end
  end

  resources :posts
  match 'admin/products/delete_products_of_the_week' => 'admin/products#delete_products_of_the_week'
  match 'admin/products/products_of_the_week' => 'admin/products#products_of_the_week'
  match '/show_order_details' => 'site/orders#show_order_details'
  match 'admin/products/products_sortby_quantity' => 'admin/products#products_sortby_quantity'
  match 'orders/review' => 'site/orders#review'
  match 'admin/xml' => 'admin/xml#index', :as => :xml

app/controllers/site/authentications_controller.rb
class Site::AuthenticationsController < ApplicationController
  def index
    @authentications = Authentication.all
  end

  def create
    omniauth = request.env["omniauth.auth"]
    authentication =
      if omniauth['provider'] == 'twitter'
        Authentication.find_by_provider_and_uid_and_token(omniauth['provider'], omniauth['uid'], omniauth['credentials']['token'])
      elsif omniauth['provider'] == 'facebook'
        Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
      end
    user = User.find_by_login(omniauth['info']['nickname'])
    session[:omniauth] = omniauth
    if authentication
      self.current_user = User.find(authentication.user_id)
      current_user.set_last_seen_at
      session[:current_user] = current_user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_url
    elsif omniauth['provider'].present? and user.present?
      flash[:notice] = "Please login"
      redirect_to "/login?login=#{user.login}&provider=#{omniauth['provider']}&uid=#{omniauth['uid']}&token=#{omniauth['credentials']['token']}"
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        redirect_to signup_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_path
  end
end

app/controllers/site/blog_controller.rb
 class Site::BlogController < ApplicationController
  layout "site"
  before_filter :store_comment, :only => :comment, :method => :post
#  before_filter :site_login_required, :only => :comment
  def index

    per_page = 25
    if params[:category] == 'search_blog_post'
      posts = Post.where("name like '%#{params[:text]}%' or friendly_identifier like '%#{params[:text]}%'")  
    elsif params[:tag_id]
      @tag = Tag.find(params[:tag_id])

       posts = @tag.posts.where(["blog_type_id = ?", 1]).order("created_at DESC").paginate(:page => params[:page], :per_page => per_page)

    elsif params[:year].blank? && params[:month].blank?
      posts = Post.where(["blog_type_id = ?", 1]).order("created_at DESC").paginate(:page => params[:page], :per_page => per_page)
    else
      @year = params[:year].to_i
      @month = params[:month].to_i
      begin_of_the_month = "1/#{@month}/#{@year}".to_time.utc
      end_of_the_month = begin_of_the_month.end_of_month.to_time.utc
     posts = Post.where("blog_type_id = ? AND created_at >= ? AND created_at <= ?", 1, begin_of_the_month.to_s(:db), end_of_the_month.to_s(:db)).paginate(:page => params[:page], :per_page => per_page)
    
    end
    @posts = posts
    
    respond_to do |wants|
      wants.html
      wants.xml { render :layout => false }
    end
  end

  def show
    store_location
    if params[:friendly_identifier]
      post = Post.find(params[:friendly_identifier])
    else
      post = Post.find(params[:id])
    end
    @post = post
    unless @post
      redirect_to "/404"
    else
      @post.count_view if @post
      @comments = @post.comments.where(reply_id: nil,public: true).paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
    end

  end

  def comment
    @post = Post.find(params[:id])
    comment_public = current_user ? current_user.admin? : false  
    @comment = Comment.new(
      :name => session[:name],
      :description => session[:description],
      :captcha => session[:captcha],
      :captcha_key => session[:captcha_key],
      :mail_check => session[:mail_check],
      :reply_id => session[:reply_id],
      :public => comment_public
    )
    @comment.post = @post if !session[:reply_id].present?
    @comment.email = current_user.email
    @comment.user_id = current_user.id
    if verify_recaptcha(model: @comment)  and @comment.save
      Notifier.comment(@comment,current_user).deliver
      flash[:notice] = "comment is successfully posted"
    elsif session[:reply_id].present?  and @comment.save
      Notifier.reply_comment(@comment,@comment.comment.user).deliver
      flash[:notice] = "comment is successfully posted"      
    else
      flash[:notice] = @comment.show_errors
     # render :action => :show
    end
      redirect_to blog_path(@post.friendly_identifier)
  end



  protected
  def store_comment

    if params[:comment]
      session[:name] = params[:comment][:name]
      session[:description] = params[:comment][:description]
      session[:captcha] = params[:comment][:captcha]
      session[:captcha_key] = params[:comment][:captcha_key]
      session[:mail_check] = params[:comment][:mail_check]
      session[:reply_id] = params[:comment][:reply_id]
    end
  end

  def check_mail_list(post, user)
    @post = Post.find(post)
    no_of_comment = @post.comments.count
    if no_of_comment == 1 
      return true
    else
      p no_of_comment

      @comments = (@post.comments).find(:all, :conditions =>[' mail_check = ?',true])
      p "********tyty***************************"
      p @comments.count
      p "**********ytyy**************************"
      for comment in @comments
        Notifier.comment(comment,user).deliver
      end
    end
  end

end

app/controllers/site/checkouts_controller.rb
class Site::CheckoutsController < ApplicationController



  before_filter :site_login_required
  before_filter :store_location
  after_filter :reset_session, :only => [:confirmed]


  #ssl_required :payment
  #ssl_required :all

  # UnComment this when site goes live
  # I think this is not working when the site is held as a sub domain of LegreenSolutions

  #Comment 2nd when we go Live
  #Now we are using this becuase https redirection is not working when site is sub domain of legreensolutions
    #ssl_allowed
    #ssl_required :all

    #ssl_allowed
    #ssl_required


  layout "site"

  def index
    unless @cart.valid?
      flash[:notice] = @cart.show_errors
      redirect_to cart_index_path
    end

    @ship_address = session[:ship_address] ||= current_user.default_ship_address
  end

  def confirm_address
    @ship_address = session[:ship_address] ||= current_user.ship_addresses.new(params[:ship_address])

    if @ship_address.valid?
       redirect_to payment_checkouts_path
    else
      flash[:notice] = @ship_address.show_errors
      redirect_to checkouts_path
   end
  end

  def payment
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @payment_method = 2 #set default payment method to credit card
  end

  def paypal
  end

  def confirmed
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @order = Order.find(:last,:conditions=>['user_id=?',current_user.id])
    @was_admin = false
    if session[:previous_admin_id]
      @was_admin = true
    end  
    revert_session
  end

  def order_confirmation
   if request.post?
    unless params[:accept].blank?
      redirect_to :controller=>'site/checkouts',:action=>'payment'
    else
      flash[:notice] = 'Please accept terms and conditions'
      #flash[:alert] = "Please accept terms and conditions"
      #redirect_to :controller=>'checkouts',:action=>'payment'
    end
   end
  end

  private
  def reset_session
    session[:ship_address] = nil
    session[:cart] = nil
  end
end

app/controllers/site/comments_controller.rb
class Site::CommentsController < ApplicationController
  before_filter :site_login_required
  def index
    @comments = Comment.where(['user_id =?',params[:id]]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html { render :layout => 'site' }
    end
  end
end

app/controllers/site/moods_controller.rb
class Site::MoodsController < ApplicationController

  layout "site"

  def index
    @moods = Mood.all
  end

end

app/views/site/shared/_box_about_us.html.erb
<div id="box_about_us" class="block">
  <%- active_uri = request.url -%>
  <h3>About Us</h3>
  <ul>
    <li><%= link_to("Our manifesto", our_principles_path, :class => ('active' if active_uri == our_principles_path)) %></li>
    <li><%= link_to("Who we are", about_us_path, :class => ('active' if active_uri == about_us_path)) %></li>
    <li><%= link_to("Meet us", meet_us_path, :class => ('active' if active_uri == meet_us_path)) %></li>
    <li><%= link_to("Contact us", contact_us_path, :class => ('active' if active_uri == contact_us_path)) %></li>
    <li><%= link_to("Wholesale", wholesale_enquiry_path, :class => ('active' if active_uri == wholesale_enquiry_path)) %></li>
    <li><%= link_to("Corporate services", corporate_path, :class => ('active' if active_uri == corporate_path)) %></li>
    <li><%= link_to("Supplier", "/supplier", :class => ('active' if active_uri == "/supplier")) %></li>
    <li><%= link_to("Guarantee of Satisfaction", guarantee_of_satisfaction_path, :class => ('active' if active_uri == guarantee_of_satisfaction_path)) %></li>
    <li><%= link_to("Gift Cards", '/wine/gift-cards', :class => ('active' if active_uri == '/wine/gift-cards')) %></li>
  </ul>
</div>

app/views/site/shared/_box_book_a_table.html.erb
<div class="block" id="box_book_a_table">
  <h1><!-- Italian wine and food Online | Award winning wine merchant -->
  What our customers say</h1>
  <div>
    The wines you have supplied have never failed to please, I dont have a clue about what grapes or where they come from, but i know that I enjoy them. 
    <br/><br/>
    <%= link_to "(View All ...)", :action => "testimonial" %>
    <br/><br/>
    Thanks Again, R. Patterson.
  </div>
</div>		

app/views/site/shared/_box_food_search.html.erb
<%= render :partial => 'site/shared/box_wine_search.html.erb' %>

app/views/site/shared/_box_mood.html.erb
<div class="col-md-4 half-on-tab">
    <div class="small-box-3 center-align">
        <%path =  get_small_box_moods_image_path%>
        <%= link_to image_tag(path ,:alt=>'Moods',:title=>'Moods'), "/moods",:title=>'Moods' -%>
    </div>
</div>

app/views/site/shared/_box_product_reviews.html.erb
<%- @category ||= Category.find(params[:category]) if params[:category] -%>
<% unless @category.blank? %>
<div class="block" id="box_event_reviews">
  <h1><%= @category.name.titleize %> reviews</h1>
  <br />
  <table>
  <%- if @category.reviews.size > 0 -%>
    <%- @category.reviews.each do |review| -%>
    <tr>
      <td>
        <%= avatar_for_user(review.user, 'small') %><br />
        <%= review.user.name %>
      </td>
      <td valign="top"><%= truncate review.description.html_safe, 20 %></td>
    </tr>
    <%- end -%>
  <%- else -%>
    <tr>
      <td>No reviews for <%= @category.name.titleize %></td>
    </tr>
  <%- end -%>
  </table>
</div>
<% end %>

app/views/site/shared/_box_search_people_by_city.html.erb
<div class="block" id="box_search_recipes_new">
	<h3>Refine search</h3>
	<%= form_tag search_index_path, :method => :get do %>
   <%= hidden_field_tag :category, "people" %>
		<table border="0" cellspacing="2" cellpadding="0">
			<tr>
			  <td>Search by city:</td>
			  <td> <%= text_field_tag :city_text, params[:city_text], :id => "search_text" %></td>
      </tr>

			<tr>
			  <td colspan="2"></td>
      </tr>
			<tr>
			  <td></td>
			  <td><%= image_submit_tag "search.png" %></td>
      </tr>
		</table>
	<% end %>
</div>

app/views/site/shared/_box_testimonial.html.erb
<div class="block" id="box_testimonial">
  <h1><!-- Italian wine and food Online | Award winning wine merchant -->
  Testimonials</h1>
  <div>
    Have not tasted Italian wines as such since visiting Italy 3 years ago 
    <%= link_to "(Read all ...)", :controller => "site/base", :action => "testimonial" %>
    <br/><br/>
    Mr. Carruthers				
    <br/>
  </div>
</div>			

app/views/site/shared/_box_wine_club_testimonials.html.erb
<%- @testimonials = Testimonial.find(:all,:conditions=>['UPPER(page_to_display) = ?','WINE CLUB'],:order=>'id DESC',:limit=>2) -%>
<div class="left-small-box hide-on-mobile">
  <h2 class="small-swiper-heading">Wine Club Testimonials</h2>
  <div  class="review-box">
      <div class="review-tex">
        <!-- Swiper -->
        <div class="swiper-container" id="thirdSwiper">
          <div class="swiper-wrapper">
            <%- if @testimonials.size > 0 -%>
              <%- @testimonials.each do |testimonial| -%>
                <div class="swiper-slide">
                  <div class="slide-text">
                    <span class="quotes-before"><img src="/images/quotes-before.png" alt="Quotes" title="Qoutes" /></span>
                    <span class="pad5-7">
                      <%= truncate(testimonial.description.html_safe, {:length => 100}) %>
                    </span>
                    <span class="quotes-after"><img src="/images/quotes-after.png" alt="Qoutes" title="Qoutes" /></span>
                  </div>
                  
                </div>
              <%- end -%>
            <%- else -%>
            <div class="slide-text">
              <span class="quotes-before"><img src="/images/quotes-before.png" alt="Qoutes" title="Qoutes" /></span>
              <span class="pad5-7">No Testimonial found for Wine Club</span>
              <span class="quotes-after"><img src="/images/quotes-after.png" alt="Qoutes" title="Qoutes" /></span>
            </div>
            <%- end -%>          
          </div>
        </div><!-- End Swiper -->
      </div>
      <div class="review-arrow">
        <!-- Add Arrows -->
        <div class="pagi-arrow2">
          <div class="swiper-button-prev"></div>
            <div class="arrow-sep"></div>
            <div class="swiper-button-next"></div>
        </div>
      </div>
    </div>
  </div>

app/views/site/shared/_box_wine_of_the_week.html.erb
<% displayed = false; week_products = WeekProduct.find(:all) %>
<% unless week_products.blank? %>
 <% week_products.each do |w_product| %>
   <% product = Product.find(w_product.week_product_id) %>
   <% if  product.categories.root.name.downcase == 'wine' %>
    <div class="block" id="wine-of-the-week">
    <% displayed = true %>
      <%= link_to((image_tag "wineoftheweek.jpg",:alt=>'Wine of the Week',:title=>'Wine of the Week'), :controller=>'site/products',:action=>'wine_of_the_week',:id=>product.id)%><br />
     <!-- ul--> <% break end %>   <%end %>
<!--  <%#- week_products.each do |w_product| -%>
   <%# product = Product.find(w_product.week_product_id) %>

   <%# if  product.categories.root.name.downcase == 'wine' %>
    <li style="margin-bottom:10px;">
    <div><%#= link_to product.name,{:controller=>'site/products',:action=>'wine_of_the_week',:id=>product.id}, {:style => "font-size:14px;color:#9b0707"} %></div>
	  </li>
	  <%# end  %>
  <%#- end -%> -->
<% if displayed == true %>
 <!--/ul--></div><br />
<%end %>
<% end %>

app/views/site/shared/_box_wine_pdf.html.erb
<% if setting = Setting.find(:first) %>
	<% if setting.wine_pdf %>
	<div>
		<div>
			<%= link_to image_tag("pdf.png"), setting.wine_pdf.public_filename %>
			<%= link_to "Download our wine list", setting.wine_pdf.public_filename %> 
		</div>
	</div>
	<% end %>
<% end %>

app/views/site/shared/_box_wine_tour_testimonials.html.erb
<% @testimonials = Testimonial.find(:all,:conditions=>['UPPER(page_to_display) = ?','WINE TOUR'],:order=>'id DESC',:limit=>2) -%>

<div class="left-small-box" id="box_event_reviews">
  <h2 class="small-swiper-heading">Wine Tour Testimonials</h2>
  <div  class="review-box">
    <div class="review-tex">
      <!-- Swiper -->
      <div class="swiper-container" id="thirdSwiper">
        <div class="swiper-wrapper">
          <%- if @testimonials.size > 0 -%>
            <%- @testimonials.each do |testimonial| -%>
              <div class="swiper-slide">
                <div class="slide-text">
                  <span class="quotes-before"><img src="/images/quotes-before.png" alt="Qoutes" title="Qoutes" /></span>
                  <span class="pad5-7">
                    <%= link_to testimonial.description.html_safe,testimonial_path, :title=>"Testimonial" %>
                  </span>
                  <span class="quotes-after"><img src="/images/quotes-after.png" alt="Qoutes" title="Qoutes"  /></span>
                </div>
              </div>
            <%- end -%>
            <%- else -%>
              <div class="slide-text">
                <span class="quotes-before"><img src="/images/quotes-before.png"  alt="Qoutes" title="Qoutes" /></span>
                  <span class="pad5-7">No Testimonial for Wine Tour</span>
                  <span class="quotes-after"><img src="/images/quotes-after.png" alt="Qoutes" title="Qoutes" /></span>
              </div>
            <%- end -%>
          </div>
        </div><!-- End Swiper -->
      </div>
      <div class="review-arrow">
        <!-- Add Arrows -->
        <div class="pagi-arrow2">
          <div class="swiper-button-prev"></div>
          <div class="arrow-sep"></div>
          <div class="swiper-button-next"></div>
        </div>
      </div>
  </div>
</div>

app/views/site/shared/_community_box.html.erb
<div class="col-md-4">
    <div class="small-box-3 center-align">
        <%path = get_small_box_community_image_path%>
        <%= link_to image_tag(path, alt:"wine Community", title:"wine Community"), "/wine-community", :title=>"Wine Community" -%>
    </div>
</div>

app/views/site/shared/_promotion.html.erb
<%if request.url.upcase != '/CHECKOUTS/CONFIRMED' %>
<%- if @cart.items.size > 0 -%>
<%- @promotion_limit = @setting.order_delivery_amount.to_f - @cart.sub_total.to_f if !@setting.nil? -%>
<%- if @promotion_limit > 0 -%>
Add another <%= number_to_currency(@promotion_limit,{:unit => "£"}) -%> and get free delivery
<%- else -%>
Your order qualifies for free delivery *
<%- end -%>
<%- else -%>
Spend <%= number_to_currency(@setting.order_delivery_amount,{:unit => "£"})  if !@setting.nil? %> and get free delivery
<%- end -%>
<% end %>

app/views/site/shared/_range_slider.html.erb
<% products = @products || @category.products %>
<% @price_opts = products.collect(&:price_discounted).flatten.sort %>
<div class="range-slider">
  <div class="black-heading-16">Price</div>
  <p>
    <label for="amount"></label>
    <input type="text" id="amount" readonly >
  </p>
  <div id="slider-range"></div>
  <div class="row clearfix range-price">
      <div class="col-xs-4 left">
          <div>|</div>
          <div>£0</div>
      </div>
      <div class="col-xs-4 center">
          <div>|</div>
          <div>£75</div>
      </div>
      <div class="col-xs-4 right">
          <div>|</div>
          <div>£150+</div>
      </div>
  </div>
</div>
<%= hidden_field_tag :start_price , '' , :class=> 'start_price' %>
<%= hidden_field_tag :end_price , '' , :class=> 'end_price' %>