config/routes.rb
ItalyabroadNew::Application.routes.draw do
  namespace :admin do
    resources :testimonials
    resources :faqs
    resources :shipping_agencies
    resources :occasions
    resources :about_us
    resources :contact_messages
    resources :regions do
      resources :images, :only => [:destroy]
    end
    resources :producers  do
      resources :images, :only => [:destroy]
    end
    resources :grapes do
      resources :images, :only => [:destroy]
    end
    resources :forums
    resources :categories
    resources :deliveries
    resources :cupons do
      match :product_list, :on => :collection
    end
    resources :forums
    resources :posts
    resources :comments
    resources :reviews do
      match :send_mails, :on => :collection
    end
    resources :orders, :only => [:index, :show, :destroy] do
      member do
        get :print_tasting
        get :print_invoice
        get :print_picking_list
        get :delivery_details
        get :cancel_delivery_charge
      end
    end
    resources :users
    resources :customers do
      collection do
        get :print_user_details
      end
    end
    resources :gift_options
    resources :subscriptions
    resources :news_letters do
      resources :images, :only => [:destroy]
    end
    resources :recipes do
      collection do 
        get 'xml'
      end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :resources, :only => [:destroy]
    resources :images, :only => [:destroy]
    resources :products do
       collection do 
          get 'xml'
        end
      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :settings, :only => [:index, :update] do
      
      collection do 
        get 'available_backups'
        get 'restore'
        get 'take_backup_now'
        get 'download'

      end

      resources :images, :only => [:destroy]
      resources :resources, :only => [:destroy]
    end
    resources :small_box_settings 
    get "moods/index"

    get "moods/new"

    post "moods/create"

    get "moods/edit"

    put "moods/update"
    delete "moods/destroy"
  end

  get "moods/index"

  resources :chat_messages do
    collection do
      get "show_alert"
      get "take_username" => "chat_messages#take_username"
    end
  end

  namespace(:admin){
    resources :wine_sizes
    resources :sommeliers
    resources :food_or_drinks
    resources :desired_expenditures
    resources :food_options
    resources :manage_sommeliers, :only => [:index, :create]
  }

  match "/auth/:provider/callback" => "site/authentications#create"

  match 'suppliers' => 'site/base#supplier', :as => :meet_us
  match 'contact-us' => 'site/base#contact', :as => :contact_us
  match 'corporate-services' => 'site/base#corporate', :as => :corporate
  match 'wholesale-enquiry' => 'site/base#enquiries', :as => :wholesale_enquiry
  match 'olive-oil-guide' => 'site/base#olive_oil_guide', :as => :olive_oil_guide
  match 'about-us' => 'site/base#about_us', :as => :about_us
  match 'our-manifesto' => 'site/base#our_principles', :as => :our_principles
  match 'meet-us' => 'site/base#meet_us', :as => :meet_us
  match 'terms-and-conditions' => 'site/base#conditions', :as => :terms_and_conditions
  match 'privacy-policy' => 'site/base#privacy', :as => :privacy_policy
  match 'delivery-services' => 'site/base#delivery_services', :as => :delivery_services
  match 'managing-account' => 'site/base#managing_account', :as => :managing_account
  match 'contact-details' => 'site/base#contact_details', :as => :contact_details
  match 'sitemap' => 'site/base#sitemap', :as => :sitemap
  match 'google_sitemap.xml' => 'site/base#google_sitemap', :defaults => {:format => :xml}
  match 'guarantee_of_satisfaction' => 'site/base#guarantee_of_satisfaction', :as => :guarantee_of_satisfaction
  match 'enable_disable_chat' => 'admin/base#enable_disable_chat', :as => :enable_disable_chat
  match 'testimonial' => 'site/testimonials#index', :as => :testimonial
  match 'popular' => 'site/base#popular', :as => :popular
  match 'signup' => 'site/customers#new', :as => :signup
  match 'login' => 'site/base#login', :as => :login
  match 'guest_login' => 'site/base#guest_login', :as => :guest_login
  match 'logout' => 'site/base#logout', :as => :logout
  match 'subscribe-dali-news' => 'site/base#subscribe', :as => :subscribe_dali_news
  match 'subscriptions' => 'site/base#create_subscription', :as => :create_subscription, :method => :post
  match 'thank-you' => 'site/base#subscription_complete', :as => :subscription_complete
  match 'unsubscribe-dali-news' => 'site/base#unsubscribe', :as => :unsubscribe_dali_news
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  match 'siteadmin' => 'admin/base#index', :as => :siteadmin
  match 'admin/login' => 'admin/base#login', :as => :admin_login
  get '/site/blog/:friendly_identifier' => 'site/blog#show'
  match 'blog/:year/:month' => 'site/blog#index', :as => :blog_by_month_page, :year => /\d{4}/, :month => /\d{1,2}/
  match 'orders/:id/invoice' => 'site/orders#invoice', :as => :print_invoice
  match 'my-account' => 'site/customers#account', :as => :account
  match 'follow/:user_id' => 'site/customers#follow', :as => :follow
  match 'unfollow/:user_id' => 'site/customers#unfollow', :as => :unfollow
  match 'grape-guide' => 'site/grapes#index', :as => :grape_guide
  match 'request-new-password' => 'site/customers#request_new_password', :as => :request_new_password
  match 'wine-events' => 'site/categories#show', :as => :wine_events, :category => 'events'
  match 'wine-community' => 'site/forums#index', :as => :wine_community
  match 'grapes/search_results' => 'site/grapes#search_results'
  get '/landing.html'=> 'site/base#landing_page'
  get '/messages/send_reply'=> 'site/messages#send_reply'
  post '/messages/send_message' => 'site/messages#send_message'

  match 'cart/gift_options' => 'site/cart#gift_options'
  match 'checkouts/order_confirmation' => 'site/checkouts#order_confirmation'
  match 'cart/update_gift' => 'site/cart#update_gift'

  scope module: 'site' do  
      resources :products, :only => [:index, :show, :wine_of_the_week, :food_of_the_week] do
        resources :reviews, :only => [:new, :create]
        resources :wine_list, :only => [:index, :create, :destroy]
        resources :wish_list, :only => [:index, :create, :destroy]
        resources :cart, :only => [:create, :update, :destroy] do
          collection do
            get :empty
          end
        end
      end

    resources :forums do
      resources :topics do
        resources :posts
        resource :monitorship
      end
    end
    resources :authentications
    resources :search, :only => [:index] do
      collection do 
        get :find_wines
        get :find_other_drinks
        get :find_users
        get :find_producers
        get :find_hampers
        get :find_foods
        get :find_recipes
        get :find_wine_events
        get :find_grapes
        get :autocomplete_search_name
        get :autocomplete_search_wine_name
        get :autocomplete_search_food_name
        get :autocomplete_search_hamper_name
        get :autocomplete_search_drinks_name
        get :autocomplete_post_name
        get :autocomplete_search_recipes_name
      end
    end
    
  
    resources :orders, :only => [:index, :new, :create, :show] do
      member do
        get :cancel_review
      end
      match :download_pdf, :on => :collection
    end
    resources :wish_list, :only => [:index, :create, :destroy]
    resources :wine_lists, :only => [:index, :create, :destroy]
    resources :reviews
    resources :cart, :only => [:index, :update] do
      collection do
        get :empty
        get :continue_shopping
        get :user_select
        post :user_select
      end
    end
    resources :cart, :only => [:create, :update, :destroy] do
      get :autocomplete_user_name, :on => :collection
      collection do
        get :empty
        get "gift_options"
      end
    end
    resources :recipes do
      collection do
        get :recipes_list
      end
    end
    resources :reviews, :only => [:new, :create]
    resources :blog, :only => [:index, :show] do
      match :comment, :on => :member
    end

    resources :producers , :only => [:show, :index]
    resources :grapes, :only => [:index, :show]
    resources :faqs
    resources :customers do
      collection do
        get :account
        get :update_default_pic
        get :request_new_password
        post :find
        post :send_message
      end
    end
    resources :products, :only => [:show]
    resources :regions, :only => [:show, :index]
    resources :checkouts, :only => [:index] do
      collection do
        post :confirm_address
        get :payment
        get :paypal
        get :confirmed
      end
    end
    resources :news_letters, :only => [:show]
    resources :ship_addresses
    resources :chat do
      match :create_chat_user, :on => :collection
      match :send_data, :on => :collection
      match :send_message, :on => :collection, :via => :post
    end
    resources :sommelier
    resources :moods, :only => :index
  end

  match 'image' => 'site/images#show', :path_prefix => ':image_type'
  resources :image, :controller => 'site/images', :only => [:show], :path_prefix => ':image_type'

  resources :posts do
    collection do
      post :search
    end
  end

  resources :posts
  match 'admin/products/delete_products_of_the_week' => 'admin/products#delete_products_of_the_week'
  match 'admin/products/products_of_the_week' => 'admin/products#products_of_the_week'
  match '/show_order_details' => 'site/orders#show_order_details'
  match 'admin/products/products_sortby_quantity' => 'admin/products#products_sortby_quantity'
  match 'orders/review' => 'site/orders#review'
  match 'admin/xml' => 'admin/xml#index', :as => :xml

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  before_filter :admin_login_required
  before_filter :store_location, :only => [:edit, :meta, :extra, :wine, :correlation, :images, :files]

  layout "admin"

  def index
    if params[:search]
      @recipes = Recipe.where(['name LIKE ?',"%#{params[:search_text]}%"]).order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    else
      @recipes = Recipe.where("").order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    end

    respond_to do |format|
      format.html
    end
  end

  def xml
    @recipes = Recipe.all.to_xml
    File.open("recipes.xml", 'w') {|f| f.write(@recipes) }
    send_file File.join(Rails.root,"recipes.xml" )
  end



  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def create
    @recipe = Recipe.new(params[:recipe])

    if @recipe.save
      redirect_to edit_admin_recipe_path(@recipe)
    else
      flash[:notice] = @recipe.show_errors
      render :action => :new
    end
  end

  def update
    params[:recipe] ||= {}
    params[:recipe][:correlation_ids] = params[:correlation_ids] if params[:correlation_ids]

    @recipe = Recipe.find(params[:id])


    @recipe.image_1.destroy if @recipe.image_1 && !params[:image_1].blank?
    @recipe.build_image_1(:image_filename => params[:image_1]) unless params[:image_1].blank?

    @recipe.image_2.destroy if @recipe.image_2 && !params[:image_2].blank?
    @recipe.build_image_2(:image_filename => params[:image_2]) unless params[:image_2].blank?

    @recipe.image_3.destroy if @recipe.image_3 && !params[:image_3].blank?
    @recipe.build_image_3(:image_filename => params[:image_3]) unless params[:image_3].blank?


    @recipe.resource_1.destroy if @recipe.resource_1 && !params[:resource_1].blank?
    @recipe.build_resource_1(params[:resource_1]) unless params[:resource_1].blank?

    @recipe.resource_2.destroy if @recipe.resource_2 && !params[:resource_2].blank?
    @recipe.build_resource_2(params[:resource_2]) unless params[:resource_2].blank?

    @recipe.resource_3.destroy if @recipe.resource_3 && !params[:resource_3].blank?
    @recipe.build_resource_3(params[:resource_3]) unless params[:resource_3].blank?

    if @recipe.update_attributes(params[:recipe])
      flash.now[:notice] = "Recipe is updated successfully"
    else
      @recipe.image_1 = nil
      @recipe.image_2 = nil
      @recipe.image_3 = nil

      @recipe.resource_1 = nil
      @recipe.resource_2 = nil
      @recipe.resource_3 = nil

      flash.now[:notice] = @recipe.show_errors
    end

    #redirect_back_or_default(admin_recipes_path)
    redirect_to edit_admin_recipe_path(@recipe)
  end

  def destroy
    Recipe.find_by_id(params[:id]).destroy
    redirect_to :action => :index
  end

  def meta
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def extra
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def wine
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def correlation
    @recipe = Recipe.find(params[:id])
    @products = @recipe.all_product_with_that_are_related

    respond_to do |format|
      format.html
    end
  end

  def images
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def files
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/site/authentications_controller.rb
class Site::AuthenticationsController < ApplicationController
  def index
    @authentications = Authentication.all
  end

  def create
    omniauth = request.env["omniauth.auth"]
    authentication =
      if omniauth['provider'] == 'twitter'
        Authentication.find_by_provider_and_uid_and_token(omniauth['provider'], omniauth['uid'], omniauth['credentials']['token'])
      elsif omniauth['provider'] == 'facebook'
        Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
      end
    user = User.find_by_login(omniauth['info']['nickname'])
    session[:omniauth] = omniauth
    if authentication
      self.current_user = User.find(authentication.user_id)
      current_user.set_last_seen_at
      session[:current_user] = current_user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_url
    elsif omniauth['provider'].present? and user.present?
      flash[:notice] = "Please login"
      redirect_to "/login?login=#{user.login}&provider=#{omniauth['provider']}&uid=#{omniauth['uid']}&token=#{omniauth['credentials']['token']}"
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        redirect_to signup_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_path
  end
end

app/controllers/site/checkouts_controller.rb
class Site::CheckoutsController < ApplicationController



  before_filter :site_login_required
  before_filter :store_location
  after_filter :reset_session, :only => [:confirmed]


  #ssl_required :payment
  #ssl_required :all

  # UnComment this when site goes live
  # I think this is not working when the site is held as a sub domain of LegreenSolutions

  #Comment 2nd when we go Live
  #Now we are using this becuase https redirection is not working when site is sub domain of legreensolutions
    #ssl_allowed
    #ssl_required :all

    #ssl_allowed
    #ssl_required


  layout "site"

  def index
    unless @cart.valid?
      flash[:notice] = @cart.show_errors
      redirect_to cart_index_path
    end

    @ship_address = session[:ship_address] ||= current_user.default_ship_address
  end

  def confirm_address
    @ship_address = session[:ship_address] ||= current_user.ship_addresses.new(params[:ship_address])

    if @ship_address.valid?
       redirect_to payment_checkouts_path
    else
      flash[:notice] = @ship_address.show_errors
      redirect_to checkouts_path
   end
  end

  def payment
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @payment_method = 2 #set default payment method to credit card
  end

  def paypal
  end

  def confirmed
    if @cart.items.size == 0
      redirect_to cart_index_path
    end
    @order = Order.find(:last,:conditions=>['user_id=?',current_user.id])
    @was_admin = false
    if session[:previous_admin_id]
      @was_admin = true
    end  
    revert_session
  end

  def order_confirmation
   if request.post?
    unless params[:accept].blank?
      redirect_to :controller=>'site/checkouts',:action=>'payment'
    else
      flash[:notice] = 'Please accept terms and conditions'
      #flash[:alert] = "Please accept terms and conditions"
      #redirect_to :controller=>'checkouts',:action=>'payment'
    end
   end
  end

  private
  def reset_session
    session[:ship_address] = nil
    session[:cart] = nil
  end
end

app/controllers/site/comments_controller.rb
class Site::CommentsController < ApplicationController
  before_filter :site_login_required
  def index
    @comments = Comment.where(['user_id =?',params[:id]]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html { render :layout => 'site' }
    end
  end
end

app/controllers/site/moods_controller.rb
class Site::MoodsController < ApplicationController

  layout "site"

  def index
    @moods = Mood.all
  end

end

app/views/site/recipes/print.html.erb
<h2><%= @recipe.name %></h2>
<div style="padding:5px;text-align:center">
	<div style="text-align:justify">
		<%= image_tag "/resources/images/#{@recipe.image_1.id}.jpg" %>
	</div>
	<% if @recipe.product %>
	
	<div style="border-bottom:1px solid #c1d830;padding:30px 0px 5px 0px; width:250px;margin:0 auto">
		<h3>Ingredients</h3>
	</div>
	<div style="padding:10px 0px 5px 0px"><%= @recipe.ingredients.gsub("\n","<br />") %></div>
	<div style="border-bottom:1px solid #c1d830;padding:30px 0px 5px 0px; width:250px;margin:0 auto">
		<h3>Preparation</h3>
	</div>
	<div style="padding:10px 0px 5px 0px"><%= @recipe.preparation.gsub("\n","<br />") %></div>
	<div style="text-align:center;padding-top:20px;font-size:12px"><b>Recommended Wine:</b> <%= link_to @recipe.product.name, :controller => :products, :action => :show, :id => @recipe.product %></div>
	<% end %>
</div>

app/views/site/recipes/recipes_list.html.erb
<% @title = "Authentic Italian recipes, pasta, antipasti, pesce, carne"; @description = "Authentic italian recipes directly from our grandma secret book, pasta, antipasti,starter, the most authentic Italian recipes for you to recreate at home the italian meal"; @keys ="pasta, lasagne, carne, bolognese, cantuccini, panettone, pandoro, fagioli, osso buco, arancini, pollo" %>

<%- @breadcrumbs = "#{link_to("Home", root_url, :title=>"Home")} &raquo; #{link_to("Recipes", '/recipes', :title=>"Recipes")}" -%>
<% @about = AboutU.find(:first, :conditions => {:link_type => "recipe"} ) %>

<div id="wineBanner">
  <span class="recipes_home_title">
   <%= @about.title rescue "Recipes"%>
   <!-- <strong style="font-size:26px;">Discover</strong> and prepare <strong style="font-size:26px;">delicious</strong><br />
    Italian dishes as our grandma would<br />
    make it with our <strong style="font-size:26px;">authentic</strong> Italian<br />
    recipes... the <strong style="font-size:26px;">best Italian recipes</strong><br /> -->

  </span>
  <% if  @about and !@about.image_id.nil? %>
  <%= link_to image_tag(image_url(:about_thumb, @about.image, :jpg)) , search_index_path(:id => "recipe") unless @about.blank? %>
  <% else %>
  <%= link_to image_tag("recipes.jpg"), search_index_path(:id => "recipe") %>
  <% end %>
</div>
<br/>
<%= render :partial => '/site/shared/box_search_recipes_new' %>

<div id="recipes_introduction">
  <h3>About Italian food</h3>
  <%= image_tag("aboutItalianFood.png", :style => "float:left;") %>
  <%= @about.description if @about %>
</div>
<div style="clear:both;"></div>
<div width="100%">
  <h3>Recipes by <%= @user.name %></h3>

    <%- @recipes.each do |recipe| -%>

        <table width="100%">
          <tr>
            <td valign="top">
              <strong><%= link_to recipe.name, recipe_path(recipe), :style => "font-size:14px;color:#003300;;" %></strong>
              <%= show_ratings(recipe, recipe.average_rating_round) if recipe.average_rating_round %><br />
              <strong>Course:</strong> <%= recipe.recipe_type.name %><br />
              <strong>Difficulty:</strong> <%= recipe.recipe_level.name %><br />
              <strong>Prep time:</strong> <%= recipe.preparation_time %> min<br/>
              <strong>Added by:</strong>
              <% if recipe.user_id == 3 %>
                Guest
              <%else%>
                <%= (recipe.user.name).capitalize rescue "Admin" %>
               &nbsp;&nbsp;&nbsp;
               <% if !recipe.user.nil? %>
               <%= link_to recipe.user.establishment_link %>
               <% end %>
                <% end %>
            </td>
            <td>
              <% if !recipe.image_1.blank? %>
              <%= link_to image_tag(image_url('recipe_thumb', recipe.image_1, :jpg)), recipe_path(recipe) %>
              <% else %>
              <%= link_to image_tag("no_images/PastaRecipe.jpg",:size => "100x75"), recipe_path(recipe) %>
              <% end %>

            </td>
          </tr>
          <tr>
            <td ><%= link_to "Ingredients and cooking instructions", recipe_path(recipe) %></td>
          </tr>
        </table>
        <br />
    <%- end -%>
</div>


<% content_for :right do %>
  <%= render :partial => '/site/shared/box_latest_recipe_reviews' %>
  <br />

  <%= link_to image_tag("shareRecipe.png"), new_recipe_path  %>
  <br />
  <%= link_to image_tag("chefProfile.png"), account_path %>
  <br />
  <%= render :partial => '/site/shared/box_subscriptions' %>
  <br />
  <%= render :partial => '/site/shared/social_follow' %>
<% end %>

app/views/site/recipes/show.html.erb
<%# @title = @recipe.page_title_formatted; @description = @recipe.meta_description_formatted; @keys = @recipe.meta_keys_formatted %>
<%# @class = "no-padding"; @breadcrumbs = "#{link_to("Home", root_url)} &raquo; #{link_to("Recipes", recipes_path)} &raquo; #{@recipe.name}" %>
<div class="row">
  <div class="share-row clearfix">
    <div class="pull-right">
      <%= render :partial => '/site/shared/social_bookmarks' %>
    </div>
  </div>
  <div class="two-colum-row clearfix">
    <div class="col-md-12">
      <div class="green-heading-with-border"><h1>Italian wine and food Online | Award winning wine merchant<%#= @recipe.name %></h1></div>
      <div class="row clearfix ingredients">
        <div class="col-xs-4 center-align">
          <% if !@recipe.image_1.blank? %>
            <%#= image_tag(image_url(:original, @recipe.image_1), :alt=>@recipe.name, :size =>"350x350" ) %>
            <img src= "<%= image_url(:original, @recipe.image_1) %>",  title = "<%= @recipe.name %>" alt="<%= @recipe.name %>" %>
          <% else %>
            <%= image_tag("no_images/PastaRecipe.jpg", :alt=>@recipe.name, :title=>@recipe.name) %>
          <% end %>
        </div>
        <div class="col-xs-8">
          <div class="green-heading-18">Ingredients:</div>
          <div><%= @recipe.ingredients.gsub("\n","<br />").html_safe() %></div>
        </div>
      </div>
      <% unless @recipe.region.nil? %>
        <h2 class="green-heading-2">Region :</h2>  
        <div class="bottom-50">
          <%= link_to @recipe.region.name, "/regions/#{@recipe.region.name.parameterize}", :title=>@recipe.region.name  %>
        </div>
      <%end%>
      <% if @recipe.correlations.size > 0 %>
        <h2 class="green-heading-2">Wine pairing suggestions</h2>
        <div class="prdoucer-products-wrapper">
          <div class="producer-products-row clearfix">
            <%- @recipe.correlations.where("").paginate(:page => params[:page], :per_page => 4).each do |product| -%>
              <div class="producer-products-col">
                <%image = Image.find_by_id(product.image_1_id) %>
                <%if image%>
                  <div class="producer-product-image"><%=image_tag image.image_filename.url %></div>
                <%end%>
                <div class="producer-product-text">
                  <%= link_to product.name, nested_products_uri(product), :title=>product.name %>
                </div>
              </div>
            <%- end -%>
          </div>
        </div>
      <% end %>
      <%if @recipe.description != '' %>
        <div class="detail-recipe">
          <h2 class="green-heading-2">Description</h2>
          <div class="bottom-50"><%=@recipe.description%></div>
        </div>
      <%end%>
      <h2 class="green-heading-2">Preparation</h2>
      <div class="bottom-50">
        <%= @recipe.preparation_cleared.html_safe() %> 
      </div>
      <%- if logged_in? -%>
        <h2 class="green-heading-2">Leave your review <%= link_to '(Add a comment)',"#",:onclick=>"document.getElementById('recipe_comments_add').style.display='block';return false;", :title=>"Add a Comment" %></h2>
        <div id="recipe_comments_add" style="display:none;">
          <div class="latest-review-box bottom-50">
            <%= render(:partial => 'site/reviews/new', :locals => {:create_url => reviews_path(@recipe, :return_to => recipe_path(@recipe)),:recipe_id => @recipe.id}) %>
          </div>
        </div>
      <%- else -%>
        <h2 class="green-heading-2">Add a comment</h2>
        <div class="bottom-50">
          <p>Comment with your account</p>
          <div><%= link_to("Login", login_path, :title=>"Login") %> || <%= link_to("Register", login_path, :title=>"Register") %></div>
        </div>
      <% end %>
      <div class="latest-review-box bottom-50">
        <%= render :partial => 'site/shared/review_view_short', :locals => {:reviewer => @recipe} %>
      </div>
    </div>
  </div>
</div>
<!-- start 3 colum  boxes-->
<div class="community-row clearfix row">
  <%= render :partial => '/site/shared/share_recipe' %>
  <%= render :partial => '/site/shared/chef_profile' %>
  <%= render :partial => '/site/shared/cercavino' %>
</div><!-- start 3 colum  boxes-->